### ISSUE TITLE
Receiving error "Update check failed. Version information file cannot be downloaded." for this plugin and this plugin only when initially launching Keepass.

### ISSUE THREAD

**Issue by paologratzi** [georgoswonkos/ExtendSelectionPlugin#1]
Pretty much covered everything in the title. When I open Keepass the initial update window shows either up to date or update available for all plugins other than ExtendSelection. I first noticed this issue about 2 weeks ago maybe. 

Thank you for the very helpful plugin btw! 
![XtndSelUpdErr](https://github.com/georgoswonkos/ExtendSelectionPlugin/assets/122838601/68daa00f-c73b-4a52-8726-a3bd6b7647cf)

**Comment by georgoswonkos** [comment]
Sorry that it took me so long, I had a lot of other projects going on. ;)
This is a nasty bug. I had never properly tested the version functionality. 
I fixed it with v. 1.0.1.
The only caveat is that you won't be notified of the new plugin version by the Keepass update check because this is what's broken in my plugin. 
Thanks for the hint!
Georg
